### ISSUE TITLE
Objects disappear too early

### ISSUE THREAD

**Issue by newnexo** [KodingKhurram/animate-dynamic#1]
Active and Dramatic animations work really well. There is only one small improvement I would like to suggest:

When the animated objects are scrolled out of the viewport, they disappear before completely exiting the viewport. That doesn't look really good, especially on larger objects. Could this be changed so that the objects scroll completely out of the viewport before disappearing?

**Comment by KodingKhurram** [comment]
Hello @newnexo ,

As discussed the mentioned issue has been resolved and I will include it in the next release.

Also, have a look at [this](https://github.com/KodingKhurram/animate.css-dynamic/pull/2)

**Comment by KodingKhurram** [comment]
This has been fixed in [v2.18.8](https://github.com/KodingKhurram/animate.css-dynamic/releases/tag/v2.18.8).
