### ISSUE TITLE
How to use aniUtil_animate() to animate elements in different sections

### ISSUE THREAD

**Issue by JarisGV** [KodingKhurram/animate-dynamic#3]
Hi @KodingKhurram 

I use to append Animate.css classes and attributes to HTML elements via JavaScript to keep HTML code clean. I can setup animations using the same code for the elements with same classes. 

For example:
If I have 3 sections with a UL with 6 elements and want to give them the same animation sequence  I just write:

`
att('.lists .via-javascript:nth-child(1)', {'class': 'via-javascript aniCus_OutIn-bounceIn-tada dur-300 loop-infinite loop-alternate del-600'});
att('.lists .via-javascript:nth-child(2)', {'class': 'via-javascript aniCus_OutIn-bounceIn-tada dur-300 loop-3x loop-alternate del-600'});
...
`

and  all the elements in the 3 sections will be animated when they come in to the viewport;
But if I use:

`
aniUtil_animate(".lists .via-javascript:nth-child(1)", "ani_rubberBand aniUtil_active aniUtil_onMouse loop-3x dur-3s");
aniUtil_animate(".lists .via-javascript:nth-child(2)", "ani_rubberBand aniUtil_active aniUtil_onMouse loop-infinite loop-alternate");
...
`

just the first UL list elements will be animated.

You can see it in action here: https://codepen.io/byJaris/pen/MWZKgdV

So, is there a way to achieve the same result using the aniUtil_animate() code scheme?

Thanks in advance and congratulations for your job with Animate.css-Dynamic

**Comment by JarisGV** [comment]
I also noticed that, in the case of using javascript and a single HTML element declared in aniUtil_animate() is not found in the DOM, the entire animation will stop working.

**Comment by KodingKhurram** [comment]
> Hi @KodingKhurram
> 
> I use to append Animate.css classes and attributes to HTML elements via JavaScript to keep HTML code clean. I can setup animations using the same code for the elements with same classes.
> 
> For example: If I have 3 sections with a UL with 6 elements and want to give them the same animation sequence I just write:
> 
> `att('.lists .via-javascript:nth-child(1)', {'class': 'via-javascript aniCus_OutIn-bounceIn-tada dur-300 loop-infinite loop-alternate del-600'}); att('.lists .via-javascript:nth-child(2)', {'class': 'via-javascript aniCus_OutIn-bounceIn-tada dur-300 loop-3x loop-alternate del-600'}); ...`
> 
> and all the elements in the 3 sections will be animated when they come in to the viewport; But if I use:
> 
> `aniUtil_animate(".lists .via-javascript:nth-child(1)", "ani_rubberBand aniUtil_active aniUtil_onMouse loop-3x dur-3s"); aniUtil_animate(".lists .via-javascript:nth-child(2)", "ani_rubberBand aniUtil_active aniUtil_onMouse loop-infinite loop-alternate"); ...`
> 
> just the first UL list elements will be animated.
> 
> You can see it in action here: https://codepen.io/byJaris/pen/MWZKgdV
> 
> So, is there a way to achieve the same result using the aniUtil_animate() code scheme?
> 
> Thanks in advance and congratulations for your job with Animate.css-Dynamic

Hello @jarisgv 

aniUtil_animate() function is used to animate a specific element, it only works for a single element, in your case, it is working only for the first UL because that is the first found element in DOM.

It is out of scope for `aniUtil_animate()` to animate multiple elements at once, However, there is an alternative for your problem. 

```
//this code will work for any number of UL you have
document.querySelectorAll(".lists .via-javascript:nth-child(6)").forEach(element => {
  aniUtil_animate(element, "ani_bounceInDownSmall aniUtil_dramatic aniUtil_active dur-2s del-1s" )
})
```

**Note** - the function you have written `att()` just adds classes to the element, while `aniUtil_animate()` is used not only to add animation classes but also to add/attach event listener to that element (dynamic event binding).

Thank you very much for your kind words and encouragement! I truly appreciate it.

**Comment by KodingKhurram** [comment]
> I also noticed that, in the case of using javascript and a single HTML element declared in aniUtil_animate() is not found in the DOM, the entire animation will stop working.

Yes, it throws up an error `Uncaught TypeError: Cannot read properties of null`, and the rest of the code is dismissed. This behavior is typical in Vanilla JavaScript.
